#
# PROGRAM:    Assigmentn 2
# PROGRAMMER: Caleb Ugent
# LOGON ID:   z1729481
# DATE DUE:   9/11/15
#

# Compiler variables
CCFLAGS = -ansi -Wall

# Rule to link object code files to create executable file
assignment9.exe: assignment9.cc assignment9.h
	g++ $(CCFLAGS) -o assignment9.exe assignment9.cc

clean:
	-rm *.exe
