#
# PROGRAM:    Assigmentn 2
# PROGRAMMER: Caleb Ugent
# LOGON ID:   z1729481
# DATE DUE:   9/11/15
#

# Compiler variables
CCFLAGS = -ansi -Wall

# Rule to link object code files to create executable file
assignment3.exe: assignment3.cc
	g++ $(CCFLAGS) -o assignnment3.exe assignment3.cc

clean:
	-rm *.exe
