#
# PROGRAM:    Assigmentn 2
# PROGRAMMER: Caleb Ugent
# LOGON ID:   z1729481
# DATE DUE:   9/11/15
#

# Compiler variables
CCFLAGS = -ansi -Wall

# Rule to link object code files to create executable file
assignmen8.exe: assignment8.cc assignment8.h
	g++ $(CCFLAGS) -o assignnment8.exe assignment8.cc

clean:
	-rm *.exe
