#
# PROGRAM:    Assigmentn 2
# PROGRAMMER: Caleb Ugent
# LOGON ID:   z1729481
# DATE DUE:   9/11/15
#

# Compiler variables
CCFLAGS = -ansi -Wall

# Rule to link object code files to create executable file
assignmen4.exe: assignment4.cc
	g++ $(CCFLAGS) -o assignnment4.exe assignment4.cc

clean:
	-rm *.exe
