#
# PROGRAM:    Assigmentn 2
# PROGRAMMER: Caleb Ugent
# LOGON ID:   z1729481
# DATE DUE:   9/11/15
#

# Compiler variables
CCFLAGS = -ansi -Wall

# Rule to link object code files to create executable file
assignmen5.exe: assignment5.cc assignment5.h
	g++ $(CCFLAGS) -o assignnment5.exe assignment5.cc

clean:
	-rm *.exe
